version: '3'

services:
  example-app:
    image: my-awesome-app
    ports:
      - 8080:8080
    volumes:
      - agent-files:/data
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/agent/libdrill_agent.so=drillInstallationDir=/data/agent,adminAddress=${DRILL_ADMIN_ADDRESS},agentId=${DRILL_AGENT_ID},buildVersion=${YOUR_APP_BUILD_VERSION}"
      # add groupId to options string above, if running multiple services
      # groupId=${DRILL_GROUP_ID}

  agent-files:
    image: drill4j/java-agent:${JAVA_AGENT_VERSION}
    volumes:
      - agent-files:/data

volumes:
  agent-files: