apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
      name: "8090"
  selector:
    {{- include "admin.selectorLabels" . | nindent 4 }}
