apiVersion: v1
kind: Service
metadata:
  labels:
    drill: frontend
  name: admin-ui
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8080
  type: NodePort  
  selector:
    drill: frontend
status:
  loadBalancer: {}
