apiVersion: v1
kind: Service
metadata:
  labels:
    drill: backend
  name: drill-admin
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  type: NodePort
  selector:
    drill: backend
status:
  loadBalancer: {}
