apiVersion: v1
kind: Service
metadata:
  labels:
    drill: spring-petclinic-sample
  name: spring-petclinic-sample
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: NodePort      
  selector:
    drill: spring-petclinic-sample
status:
  loadBalancer: {}
