apiVersion: v1
kind: Service
metadata:
  labels:
    drill: ssl-proxy
  name: ssl-proxy
spec:
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    drill: ssl-proxy
status:
  loadBalancer: {}
