apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-files
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi