apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drill-storage
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi